services:
  - type: web
    name: neuratek-calendar-middleware
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: service_account.json
    autoDeploy: true
